import {
  AiOutlineCalendar,
  AiOutlineShoppingCart,
  AiOutlineAreaChart,
  AiOutlineBarChart,
  AiOutlineStock,
} from "react-icons/ai";
import {
  FiShoppingBag,
  FiEdit,
  FiPieChart,
  FiBarChart,
  FiCreditCard,
  FiStar,
  FiShoppingCart,
} from "react-icons/fi";
import {
  BsKanban,
  BsBarChart,
  BsBoxSeam,
  BsCurrencyDollar,
  BsShield,
  BsChatLeft,
} from "react-icons/bs";
import { BiColorFill } from "react-icons/bi";
import { IoMdContacts } from "react-icons/io";
import { RiContactsLine, RiStockLine } from "react-icons/ri";
import { MdOutlineSupervisorAccount } from "react-icons/md";
import { HiOutlineRefresh } from "react-icons/hi";
import { TiTick } from "react-icons/ti";
import { GiLouvrePyramid } from "react-icons/gi";
import { GrLocation } from "react-icons/gr";
export const productData = [
  {
    id: 1,
    product_name: "odio odio elementum eu",
    brand: "Lajo",
    price: 652.26,
    quantity: 72,
    description:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    weight: 85.3,
    color: "yellow",
    size: "medium",
    material: "polyester",
    category: "grooming",
  },
  {
    id: 2,
    product_name: "imperdiet et commodo vulputate",
    brand: "Jaloo",
    price: 762.3,
    quantity: 28,
    description:
      "Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    weight: 58.2,
    color: "yellow",
    size: "small",
    material: "leather",
    category: "toys",
  },
  {
    id: 3,
    product_name: "pellentesque quisque porta volutpat erat",
    brand: "Flipbug",
    price: 571.37,
    quantity: 25,
    description:
      "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    weight: 65.5,
    color: "green",
    size: "medium",
    material: "nylon",
    category: "toys",
  },
  {
    id: 4,
    product_name: "risus praesent lectus vestibulum",
    brand: "Skippad",
    price: 456.03,
    quantity: 65,
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
    weight: 82.0,
    color: "green",
    size: "large",
    material: "leather",
    category: "toys",
  },
  {
    id: 5,
    product_name: "sed sagittis nam congue risus",
    brand: "DabZ",
    price: 701.25,
    quantity: 93,
    description:
      "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    weight: 59.8,
    color: "green",
    size: "medium",
    material: "leather",
    category: "food",
  },
  {
    id: 6,
    product_name: "vehicula condimentum curabitur in libero",
    brand: "Ainyx",
    price: 376.73,
    quantity: 74,
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    weight: 93.1,
    color: "blue",
    size: "medium",
    material: "nylon",
    category: "food",
  },
  {
    id: 7,
    product_name: "et ultrices posuere cubilia curae",
    brand: "Yamia",
    price: 317.1,
    quantity: 14,
    description:
      "Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    weight: 3.4,
    color: "pink",
    size: "large",
    material: "leather",
    category: "food",
  },
  {
    id: 8,
    product_name: "nulla eget eros elementum",
    brand: "Realfire",
    price: 210.11,
    quantity: 96,
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    weight: 2.8,
    color: "green",
    size: "large",
    material: "cotton",
    category: "accessories",
  },
  {
    id: 9,
    product_name: "quis lectus suspendisse potenti in",
    brand: "Dynabox",
    price: 860.51,
    quantity: 94,
    description:
      "Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
    weight: 58.0,
    color: "blue",
    size: "large",
    material: "cotton",
    category: "grooming",
  },
  {
    id: 10,
    product_name: "faucibus orci luctus",
    brand: "Jaloo",
    price: 322.75,
    quantity: 38,
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    weight: 54.3,
    color: "blue",
    size: "large",
    material: "nylon",
    category: "accessories",
  },
  {
    id: 11,
    product_name: "tortor eu pede",
    brand: "Voolith",
    price: 462.74,
    quantity: 99,
    description:
      "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
    weight: 78.1,
    color: "yellow",
    size: "small",
    material: "leather",
    category: "accessories",
  },
  {
    id: 12,
    product_name: "lorem integer tincidunt ante",
    brand: "Livetube",
    price: 6.26,
    quantity: 75,
    description:
      "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.",
    weight: 70.1,
    color: "yellow",
    size: "large",
    material: "nylon",
    category: "toys",
  },
  {
    id: 13,
    product_name: "pede venenatis non sodales sed",
    brand: "Zoomdog",
    price: 600.47,
    quantity: 10,
    description:
      "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.",
    weight: 26.2,
    color: "green",
    size: "large",
    material: "nylon",
    category: "toys",
  },
  {
    id: 14,
    product_name: "quam fringilla rhoncus mauris enim",
    brand: "Skynoodle",
    price: 873.75,
    quantity: 20,
    description:
      "Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    weight: 71.0,
    color: "blue",
    size: "medium",
    material: "nylon",
    category: "food",
  },
  {
    id: 15,
    product_name: "etiam vel augue vestibulum",
    brand: "Browsedrive",
    price: 783.01,
    quantity: 26,
    description:
      "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
    weight: 95.6,
    color: "pink",
    size: "large",
    material: "cotton",
    category: "accessories",
  },
  {
    id: 16,
    product_name: "aliquam quis turpis eget elit",
    brand: "Digitube",
    price: 819.28,
    quantity: 95,
    description:
      "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.",
    weight: 43.1,
    color: "green",
    size: "medium",
    material: "cotton",
    category: "accessories",
  },
  {
    id: 17,
    product_name: "tellus in sagittis",
    brand: "Zoonoodle",
    price: 292.84,
    quantity: 52,
    description:
      "Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.",
    weight: 96.9,
    color: "yellow",
    size: "small",
    material: "cotton",
    category: "food",
  },
  {
    id: 18,
    product_name: "cum sociis natoque",
    brand: "Wordpedia",
    price: 30.57,
    quantity: 14,
    description:
      "Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
    weight: 18.3,
    color: "green",
    size: "small",
    material: "cotton",
    category: "food",
  },
  {
    id: 19,
    product_name: "justo etiam pretium iaculis",
    brand: "Jaloo",
    price: 56.67,
    quantity: 42,
    description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.",
    weight: 57.0,
    color: "yellow",
    size: "small",
    material: "cotton",
    category: "accessories",
  },
  {
    id: 20,
    product_name: "nam dui proin leo odio",
    brand: "Gabvine",
    price: 528.03,
    quantity: 37,
    description:
      "Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    weight: 99.3,
    color: "yellow",
    size: "medium",
    material: "cotton",
    category: "toys",
  },
  {
    id: 21,
    product_name: "mi nulla ac enim in",
    brand: "Babbleblab",
    price: 9.78,
    quantity: 49,
    description:
      "Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    weight: 92.0,
    color: "blue",
    size: "medium",
    material: "cotton",
    category: "food",
  },
  {
    id: 22,
    product_name: "pretium nisl ut",
    brand: "Realcube",
    price: 617.68,
    quantity: 75,
    description:
      "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.",
    weight: 95.1,
    color: "green",
    size: "large",
    material: "cotton",
    category: "accessories",
  },
  {
    id: 23,
    product_name: "velit eu est",
    brand: "Yodel",
    price: 159.32,
    quantity: 73,
    description: "Aenean sit amet justo.",
    weight: 54.0,
    color: "blue",
    size: "large",
    material: "nylon",
    category: "toys",
  },
  {
    id: 24,
    product_name: "aliquet maecenas leo odio",
    brand: "Skyble",
    price: 230.21,
    quantity: 36,
    description:
      "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",
    weight: 80.9,
    color: "green",
    size: "small",
    material: "cotton",
    category: "food",
  },
  {
    id: 25,
    product_name: "at ipsum ac tellus semper",
    brand: "Skyble",
    price: 904.84,
    quantity: 16,
    description:
      "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    weight: 91.9,
    color: "green",
    size: "large",
    material: "leather",
    category: "grooming",
  },
  {
    id: 26,
    product_name: "sapien cursus vestibulum proin",
    brand: "Vitz",
    price: 770.7,
    quantity: 35,
    description:
      "Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    weight: 12.4,
    color: "red",
    size: "small",
    material: "nylon",
    category: "accessories",
  },
  {
    id: 27,
    product_name: "adipiscing elit proin interdum",
    brand: "Mybuzz",
    price: 337.73,
    quantity: 34,
    description:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.",
    weight: 81.2,
    color: "red",
    size: "medium",
    material: "cotton",
    category: "toys",
  },
  {
    id: 28,
    product_name: "consequat ut nulla",
    brand: "Topicstorm",
    price: 290.57,
    quantity: 15,
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    weight: 76.4,
    color: "yellow",
    size: "large",
    material: "cotton",
    category: "accessories",
  },
  {
    id: 29,
    product_name: "at feugiat non pretium",
    brand: "Innotype",
    price: 852.22,
    quantity: 94,
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    weight: 40.0,
    color: "red",
    size: "large",
    material: "nylon",
    category: "accessories",
  },
  {
    id: 30,
    product_name: "lacinia erat vestibulum sed",
    brand: "Rhyloo",
    price: 93.94,
    quantity: 57,
    description:
      "Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",
    weight: 28.9,
    color: "blue",
    size: "small",
    material: "polyester",
    category: "accessories",
  },
  {
    id: 31,
    product_name: "urna pretium nisl",
    brand: "Dazzlesphere",
    price: 68.29,
    quantity: 100,
    description:
      "Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    weight: 70.7,
    color: "green",
    size: "small",
    material: "leather",
    category: "grooming",
  },
  {
    id: 32,
    product_name: "sapien cursus vestibulum",
    brand: "Innojam",
    price: 528.7,
    quantity: 3,
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    weight: 48.2,
    color: "yellow",
    size: "small",
    material: "polyester",
    category: "accessories",
  },
  {
    id: 33,
    product_name: "habitasse platea dictumst morbi vestibulum",
    brand: "Vipe",
    price: 241.68,
    quantity: 12,
    description: "Duis bibendum.",
    weight: 44.0,
    color: "green",
    size: "medium",
    material: "nylon",
    category: "toys",
  },
  {
    id: 34,
    product_name: "id justo sit",
    brand: "Quinu",
    price: 539.91,
    quantity: 73,
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
    weight: 75.7,
    color: "blue",
    size: "small",
    material: "cotton",
    category: "toys",
  },
  {
    id: 35,
    product_name: "a nibh in quis justo",
    brand: "Yombu",
    price: 651.53,
    quantity: 8,
    description:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
    weight: 95.4,
    color: "pink",
    size: "medium",
    material: "leather",
    category: "accessories",
  },
  {
    id: 36,
    product_name: "porta volutpat quam pede",
    brand: "Plajo",
    price: 903.9,
    quantity: 58,
    description:
      "Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    weight: 28.4,
    color: "blue",
    size: "medium",
    material: "cotton",
    category: "food",
  },
  {
    id: 37,
    product_name: "ipsum primis in",
    brand: "Zoomlounge",
    price: 393.32,
    quantity: 24,
    description:
      "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.",
    weight: 6.4,
    color: "red",
    size: "small",
    material: "leather",
    category: "accessories",
  },
  {
    id: 38,
    product_name: "erat eros viverra eget congue",
    brand: "Gigabox",
    price: 560.32,
    quantity: 13,
    description:
      "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    weight: 34.2,
    color: "yellow",
    size: "small",
    material: "leather",
    category: "accessories",
  },
  {
    id: 39,
    product_name: "dolor sit amet",
    brand: "Yoveo",
    price: 568.0,
    quantity: 86,
    description:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    weight: 27.6,
    color: "red",
    size: "large",
    material: "leather",
    category: "food",
  },
  {
    id: 40,
    product_name: "velit id pretium iaculis",
    brand: "Feedspan",
    price: 731.5,
    quantity: 75,
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    weight: 83.5,
    color: "pink",
    size: "small",
    material: "cotton",
    category: "accessories",
  },
  {
    id: 41,
    product_name: "quam sollicitudin vitae consectetuer",
    brand: "Devpoint",
    price: 912.48,
    quantity: 73,
    description:
      "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    weight: 84.6,
    color: "blue",
    size: "medium",
    material: "polyester",
    category: "accessories",
  },
  {
    id: 42,
    product_name: "ligula sit amet",
    brand: "Bubbletube",
    price: 570.49,
    quantity: 47,
    description: "Aenean auctor gravida sem.",
    weight: 30.8,
    color: "yellow",
    size: "large",
    material: "polyester",
    category: "toys",
  },
  {
    id: 43,
    product_name: "pede lobortis ligula sit",
    brand: "Quinu",
    price: 99.16,
    quantity: 17,
    description:
      "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
    weight: 63.1,
    color: "green",
    size: "medium",
    material: "leather",
    category: "grooming",
  },
  {
    id: 44,
    product_name: "laoreet ut rhoncus aliquet pulvinar",
    brand: "Tagfeed",
    price: 92.66,
    quantity: 97,
    description:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    weight: 37.5,
    color: "yellow",
    size: "small",
    material: "cotton",
    category: "food",
  },
  {
    id: 45,
    product_name: "eu interdum eu",
    brand: "Feedfire",
    price: 461.07,
    quantity: 2,
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    weight: 74.2,
    color: "pink",
    size: "small",
    material: "nylon",
    category: "food",
  },
  {
    id: 46,
    product_name: "ullamcorper augue a suscipit nulla",
    brand: "Kazu",
    price: 247.88,
    quantity: 13,
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    weight: 25.9,
    color: "green",
    size: "large",
    material: "nylon",
    category: "grooming",
  },
  {
    id: 47,
    product_name: "odio donec vitae",
    brand: "Trilia",
    price: 786.88,
    quantity: 13,
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.",
    weight: 11.1,
    color: "red",
    size: "small",
    material: "cotton",
    category: "food",
  },
  {
    id: 48,
    product_name: "velit donec diam neque vestibulum",
    brand: "Dabfeed",
    price: 418.15,
    quantity: 51,
    description: "In quis justo. Maecenas rhoncus aliquam lacus.",
    weight: 19.4,
    color: "green",
    size: "medium",
    material: "polyester",
    category: "toys",
  },
  {
    id: 49,
    product_name: "ut at dolor",
    brand: "InnoZ",
    price: 98.8,
    quantity: 28,
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    weight: 29.8,
    color: "green",
    size: "small",
    material: "nylon",
    category: "food",
  },
  {
    id: 50,
    product_name: "vestibulum proin eu mi nulla",
    brand: "Quinu",
    price: 542.07,
    quantity: 39,
    description:
      "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    weight: 21.2,
    color: "green",
    size: "medium",
    material: "nylon",
    category: "food",
  },
];

export const serviceData = [
  {
    id: 1,
    service_name: "Distributed zero defect archive",
    complete_time: 9,
    price: 959,
    category: "spa",
  },
  {
    id: 2,
    service_name: "Operative global middleware",
    complete_time: 1,
    price: 580,
    category: "thú y",
  },
  {
    id: 3,
    service_name: "Business-focused contextually-based matrix",
    complete_time: 3,
    price: 20,
    category: "cắt lông",
  },
  {
    id: 4,
    service_name: "Switchable attitude-oriented pricing structure",
    complete_time: 7,
    price: 709,
    category: "thú y",
  },
  {
    id: 5,
    service_name: "Ameliorated optimizing protocol",
    complete_time: 10,
    price: 991,
    category: "spa",
  },
  {
    id: 6,
    service_name: "Virtual radical hardware",
    complete_time: 4,
    price: 929,
    category: "spa",
  },
  {
    id: 7,
    service_name: "Inverse regional workforce",
    complete_time: 2,
    price: 21,
    category: "spa",
  },
  {
    id: 8,
    service_name: "Diverse scalable process improvement",
    complete_time: 0,
    price: 928,
    category: "cắt lông",
  },
  {
    id: 9,
    service_name: "Reactive exuding database",
    complete_time: 6,
    price: 292,
    category: "cắt lông",
  },
  {
    id: 10,
    service_name: "Persevering motivating array",
    complete_time: 3,
    price: 952,
    category: "cắt lông",
  },
  {
    id: 11,
    service_name: "Cross-group regional approach",
    complete_time: 6,
    price: 42,
    category: "thú y",
  },
  {
    id: 12,
    service_name: "Mandatory human-resource adapter",
    complete_time: 9,
    price: 562,
    category: "chỗ ở",
  },
  {
    id: 13,
    service_name: "Ergonomic neutral installation",
    complete_time: 1,
    price: 440,
    category: "tắm rửa",
  },
  {
    id: 14,
    service_name: "Multi-channelled holistic frame",
    complete_time: 8,
    price: 703,
    category: "spa",
  },
  {
    id: 15,
    service_name: "Open-architected stable service-desk",
    complete_time: 10,
    price: 739,
    category: "thú y",
  },
  {
    id: 16,
    service_name: "Right-sized asynchronous help-desk",
    complete_time: 2,
    price: 443,
    category: "tắm rửa",
  },
  {
    id: 17,
    service_name: "Business-focused disintermediate leverage",
    complete_time: 10,
    price: 172,
    category: "spa",
  },
  {
    id: 18,
    service_name: "Reduced scalable moderator",
    complete_time: 10,
    price: 877,
    category: "tắm rửa",
  },
  {
    id: 19,
    service_name: "Total grid-enabled open system",
    complete_time: 7,
    price: 208,
    category: "tắm rửa",
  },
  {
    id: 20,
    service_name: "Polarised methodical emulation",
    complete_time: 8,
    price: 770,
    category: "cắt lông",
  },
  {
    id: 21,
    service_name: "Cross-platform zero administration challenge",
    complete_time: 3,
    price: 830,
    category: "tắm rửa",
  },
  {
    id: 22,
    service_name: "User-centric optimal strategy",
    complete_time: 9,
    price: 291,
    category: "thú y",
  },
  {
    id: 23,
    service_name: "Implemented coherent protocol",
    complete_time: 7,
    price: 117,
    category: "thú y",
  },
  {
    id: 24,
    service_name: "Mandatory fault-tolerant parallelism",
    complete_time: 8,
    price: 852,
    category: "chỗ ở",
  },
  {
    id: 25,
    service_name: "Business-focused eco-centric task-force",
    complete_time: 6,
    price: 900,
    category: "cắt lông",
  },
  {
    id: 26,
    service_name: "Implemented uniform definition",
    complete_time: 8,
    price: 501,
    category: "chỗ ở",
  },
  {
    id: 27,
    service_name: "Multi-layered static help-desk",
    complete_time: 0,
    price: 986,
    category: "thú y",
  },
  {
    id: 28,
    service_name: "Diverse foreground data-warehouse",
    complete_time: 8,
    price: 482,
    category: "spa",
  },
  {
    id: 29,
    service_name: "Proactive tangible approach",
    complete_time: 8,
    price: 604,
    category: "thú y",
  },
  {
    id: 30,
    service_name: "Configurable client-driven ability",
    complete_time: 0,
    price: 526,
    category: "spa",
  },
  {
    id: 31,
    service_name: "Stand-alone full-range secured line",
    complete_time: 2,
    price: 135,
    category: "cắt lông",
  },
  {
    id: 32,
    service_name: "User-centric tertiary productivity",
    complete_time: 4,
    price: 327,
    category: "tắm rửa",
  },
  {
    id: 33,
    service_name: "Pre-emptive next generation focus group",
    complete_time: 6,
    price: 74,
    category: "thú y",
  },
  {
    id: 34,
    service_name: "Business-focused 24 hour service-desk",
    complete_time: 5,
    price: 97,
    category: "tắm rửa",
  },
  {
    id: 35,
    service_name: "Organic multimedia data-warehouse",
    complete_time: 6,
    price: 760,
    category: "thú y",
  },
  {
    id: 36,
    service_name: "Face to face stable utilisation",
    complete_time: 6,
    price: 874,
    category: "tắm rửa",
  },
  {
    id: 37,
    service_name: "Intuitive non-volatile approach",
    complete_time: 5,
    price: 589,
    category: "thú y",
  },
  {
    id: 38,
    service_name: "Open-architected mobile software",
    complete_time: 10,
    price: 650,
    category: "thú y",
  },
  {
    id: 39,
    service_name: "Cloned systematic paradigm",
    complete_time: 6,
    price: 986,
    category: "thú y",
  },
  {
    id: 40,
    service_name: "Integrated 3rd generation collaboration",
    complete_time: 6,
    price: 490,
    category: "tắm rửa",
  },
  {
    id: 41,
    service_name: "Quality-focused cohesive Graphic Interface",
    complete_time: 10,
    price: 382,
    category: "chỗ ở",
  },
  {
    id: 42,
    service_name: "Integrated directional orchestration",
    complete_time: 10,
    price: 602,
    category: "thú y",
  },
  {
    id: 43,
    service_name: "Total multi-tasking database",
    complete_time: 3,
    price: 747,
    category: "spa",
  },
  {
    id: 44,
    service_name: "Mandatory grid-enabled collaboration",
    complete_time: 2,
    price: 862,
    category: "thú y",
  },
  {
    id: 45,
    service_name: "Cross-platform 24 hour data-warehouse",
    complete_time: 1,
    price: 718,
    category: "spa",
  },
  {
    id: 46,
    service_name: "Pre-emptive foreground application",
    complete_time: 9,
    price: 755,
    category: "tắm rửa",
  },
  {
    id: 47,
    service_name: "Object-based holistic focus group",
    complete_time: 6,
    price: 336,
    category: "chỗ ở",
  },
  {
    id: 48,
    service_name: "Exclusive system-worthy knowledge user",
    complete_time: 1,
    price: 556,
    category: "spa",
  },
  {
    id: 49,
    service_name: "Profound leading edge matrix",
    complete_time: 4,
    price: 411,
    category: "tắm rửa",
  },
  {
    id: 50,
    service_name: "Exclusive attitude-oriented local area network",
    complete_time: 1,
    price: 331,
    category: "thú y",
  },
];

export const employeeData = [
  {
    id: 1,
    first_name: "Gabrielle",
    last_name: "Darlow",
    age: 21,
    email: "gdarlow0@springer.com",
    position: "Bán hàng",
  },
  {
    id: 2,
    first_name: "Bobby",
    last_name: "Keiling",
    age: 62,
    email: "bkeiling1@telegraph.co.uk",
    position: "Chăm sóc",
  },
  {
    id: 3,
    first_name: "Melodie",
    last_name: "Iscowitz",
    age: 47,
    email: "miscowitz2@icq.com",
    position: "Chăm sóc",
  },
  {
    id: 4,
    first_name: "Stearn",
    last_name: "Lamberteschi",
    age: 53,
    email: "slamberteschi3@tinyurl.com",
    position: "Bán hàng",
  },
  {
    id: 5,
    first_name: "Dorita",
    last_name: "Lamberton",
    age: 50,
    email: "dlamberton4@google.cn",
    position: "Bán hàng",
  },
  {
    id: 6,
    first_name: "Magdaia",
    last_name: "Tregiddo",
    age: 49,
    email: "mtregiddo5@opera.com",
    position: "Chăm sóc",
  },
  {
    id: 7,
    first_name: "Emmanuel",
    last_name: "Epsly",
    age: 45,
    email: "eepsly6@technorati.com",
    position: "Chăm sóc",
  },
  {
    id: 8,
    first_name: "Brendis",
    last_name: "McGloughlin",
    age: 21,
    email: "bmcgloughlin7@cdbaby.com",
    position: "Chăm sóc",
  },
  {
    id: 9,
    first_name: "Rochella",
    last_name: "Fibbens",
    age: 23,
    email: "rfibbens8@tinyurl.com",
    position: "Bán hàng",
  },
  {
    id: 10,
    first_name: "Izaak",
    last_name: "Donwell",
    age: 23,
    email: "idonwell9@sourceforge.net",
    position: "Chăm sóc",
  },
  {
    id: 11,
    first_name: "Emmy",
    last_name: "Macci",
    age: 38,
    email: "emaccia@chron.com",
    position: "Bán hàng",
  },
  {
    id: 12,
    first_name: "Marc",
    last_name: "Christal",
    age: 46,
    email: "mchristalb@ucsd.edu",
    position: "Chăm sóc",
  },
  {
    id: 13,
    first_name: "Brett",
    last_name: "Leonarde",
    age: 52,
    email: "bleonardec@fc2.com",
    position: "Bán hàng",
  },
  {
    id: 14,
    first_name: "Cleavland",
    last_name: "Espie",
    age: 46,
    email: "cespied@tmall.com",
    position: "Bán hàng",
  },
  {
    id: 15,
    first_name: "Haily",
    last_name: "Veasey",
    age: 65,
    email: "hveaseye@sogou.com",
    position: "Bán hàng",
  },
];
export const earningData = [
  {
    icon: <MdOutlineSupervisorAccount />,
    amount: "214",
    percentage: "-4%",
    title: "Khách hàng",
    iconColor: "#03C9D7",
    iconBg: "#E5FAFB",
  },
  {
    icon: <BsBoxSeam />,
    amount: "953",
    percentage: "+13%",
    title: "Sản phẩm",
    iconColor: "rgb(255, 244, 229)",
    iconBg: "rgb(254, 201, 15)",
  },
  {
    icon: <FiBarChart />,
    amount: "17.534.000 VND",
    percentage: "+38%",
    title: "Doanh số",
    iconColor: "rgb(228, 106, 118)",
    iconBg: "rgb(255, 244, 229)",

    pcColor: "green-600",
  },
  {
    icon: <HiOutlineRefresh />,
    amount: "14.350.000 VND",
    percentage: "-12%",
    title: "Lợi nhuận",
    iconColor: "rgb(0, 194, 146)",
    iconBg: "rgb(235, 250, 242)",
    pcColor: "red-600",
  },
];

let lineChartData = [
  [
    { x: new Date(2005, 0, 1), y: 21 },
    { x: new Date(2006, 0, 1), y: 24 },
    { x: new Date(2007, 0, 1), y: 36 },
    { x: new Date(2008, 0, 1), y: 38 },
    { x: new Date(2009, 0, 1), y: 40 },
    { x: new Date(2010, 0, 1), y: 35 },
    { x: new Date(2011, 0, 1), y: 42 },
  ],
  [
    { x: new Date(2005, 0, 1), y: 28 },
    { x: new Date(2006, 0, 1), y: 21 },
    { x: new Date(2007, 0, 1), y: 25 },
    { x: new Date(2008, 0, 1), y: 32 },
    { x: new Date(2009, 0, 1), y: 40 },
    { x: new Date(2010, 0, 1), y: 24 },
    { x: new Date(2011, 0, 1), y: 30 },
  ],
];
const lineChartData2 = [
  [
    { x: new Date(2005, 0, 1), y: 21 },
    { x: new Date(2005, 1, 1), y: 24 },
    { x: new Date(2005, 2, 1), y: 36 },
    { x: new Date(2005, 3, 1), y: 38 },
    { x: new Date(2005, 4, 1), y: 40 },
    { x: new Date(2005, 5, 1), y: 35 },
    { x: new Date(2005, 6, 1), y: 42 },
  ],
  [
    { x: new Date(2005, 0, 1), y: 28 },
    { x: new Date(2005, 1, 1), y: 21 },
    { x: new Date(2005, 2, 1), y: 25 },
    { x: new Date(2005, 3, 1), y: 32 },
    { x: new Date(2005, 4, 1), y: 40 },
    { x: new Date(2005, 5, 1), y: 24 },
    { x: new Date(2005, 6, 1), y: 30 },
  ],
];
lineChartData.push(
  lineChartData[0].map((point, index) => ({
    x: point.x,
    y: point.y + lineChartData[1][index].y,
  }))
);
export const lineCustomSeries = [
  {
    dataSource: lineChartData[0],
    xName: "x",
    yName: "y",
    name: "Lợi nhuận",
    width: "2",
    marker: { visible: true, width: 10, height: 10 },
    type: "Line",
  },

  {
    dataSource: lineChartData[1],
    xName: "x",
    yName: "y",
    name: "Doanh thu",
    width: "2",
    marker: { visible: true, width: 10, height: 10 },
    type: "Line",
  },
];
export const lineCustomSeries2 = [
  {
    dataSource: lineChartData2[0],
    xName: "x",
    yName: "y",
    name: "Lợi nhuận",
    width: "2",
    marker: { visible: true, width: 10, height: 10 },
    type: "Line",
  },

  {
    dataSource: lineChartData2[1],
    xName: "x",
    yName: "y",
    name: "Doanh thu",
    width: "2",
    marker: { visible: true, width: 10, height: 10 },
    type: "Line",
  },
];

export const LinePrimaryXAxis = {
  valueType: "DateTime",
  labelFormat: "y",
  intervalType: "Years",
  edgeLabelPlacement: "Shift",
  majorGridLines: { width: 0 },
  background: "white",
};

export const LinePrimaryYAxis = {
  labelFormat: "{value} Triệu VND ",
  rangePadding: "None",
  minimum: 0,
  maximum: 100,
  interval: 20,
  lineStyle: { width: 0 },
  majorTickLines: { width: 0 },
  minorTickLines: { width: 0 },
};
export const LinePrimaryXAxis2 = {
  valueType: "DateTime",
  labelFormat: "M",
  intervalType: "Months",
  edgeLabelPlacement: "Shift",
  majorGridLines: { width: 0 },
  background: "white",
};
export const mockBarData = [
  {
    month: "Sep",
    foods: 137,
    foodsColor: "hsl(229, 70%, 50%)",
    toys: 96,
    toysColor: "hsl(296, 70%, 50%)",
    accesories: 72,
    accesoriesColor: "hsl(97, 70%, 50%)",
    cages: 140,
    cagesColor: "hsl(340, 70%, 50%)",
  },
  {
    month: "Oct",
    foods: 55,
    foodsColor: "hsl(307, 70%, 50%)",
    toys: 28,
    toysColor: "hsl(111, 70%, 50%)",
    accesories: 58,
    accesoriesColor: "hsl(273, 70%, 50%)",
    cages: 29,
    cagesColor: "hsl(275, 70%, 50%)",
  },
  {
    month: "Nov",
    foods: 109,
    foodsColor: "hsl(72, 70%, 50%)",
    toys: 23,
    toysColor: "hsl(96, 70%, 50%)",
    accesories: 34,
    accesoriesColor: "hsl(106, 70%, 50%)",
    cages: 152,
    cagesColor: "hsl(256, 70%, 50%)",
  },
  {
    month: "Dec",
    foods: 133,
    foodsColor: "hsl(257, 70%, 50%)",
    toys: 52,
    toysColor: "hsl(326, 70%, 50%)",
    accesories: 43,
    accesoriesColor: "hsl(110, 70%, 50%)",
    cages: 83,
    cagesColor: "hsl(9, 70%, 50%)",
  },
];
